@echo off
echo Starting Lux - AI Revolution Backend...
cd backend
if not exist "venv" (
    echo Creating Python Virtual Environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Launching Server...
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
